#!/bin/bash 
#PBS -l nodes=nano3:ppn=1:gpus=1,walltime=330000
#PBS -M ruilan2@illinois.edu
#PBS -N sr_in007

source /home/nie1/anaconda3/etc/profile.d/conda.sh
conda activate pytorch-CycleGAN-and-pix2pix
cd /home/nie1/pytorch-CycleGAN-and-pix2pix
CUDA_VISIBLE_DEVICES=1 python train.py --dataroot ./datasets/mat_data --name sr_in007 --model pix2pix --direction AtoB --netG resnet_9blocks --norm instance --dataset_mode template
